vcs: git

prerequisites:
  - working-copy-check
  - display-last-changes

version-generator:
  semantic:
    allow-label: true
version-persister:
  vcs-tag:
    tag-prefix: 'v'
post-release-actions:
  vcs-publish:
    ask-confirmation: true
