_welcome:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: nelmio_api_doc_index
        permanent: true # this for 301

user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     rest

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc
