---
- name: Configure Xdebug
  action: apt pkg=php5-xdebug state=installed

- lineinfile: dest=/etc/php5/mods-available/xdebug.ini line="{{ item }}" backup=yes
  with_items:
    - xdebug.remote_autostart=1
    - xdebug.cli_color=1
    - xdebug.remote_enable=1
    - xdebug.remote_connect_back=1
    - xdebug.remote_port=9000
    - xdebug.idekey=default
    - xdebug.show_local_vars=0
    - xdebug.var_display_max_data=10000
    - xdebug.var_display_max_depth=20
    - xdebug.show_exception_trace=0
