services:
  app.manager.membership:
    class: AppBundle\Manager\MembershipManager
    arguments: ["@doctrine", "@event_dispatcher"]

  app.manager.user_group:
    class: AppBundle\Manager\UserGroupManager
    arguments: ["@doctrine"]

  app.manager.notification:
    class: AppBundle\Manager\NotificationManager
    arguments: ["@doctrine", "@event_dispatcher", "@app.manager.membership"]

  app.event.user:
    class: AppBundle\EventSubscriber\UserActivitySubscriber
    arguments: ["@doctrine", "@logger"]
    tags:
        - { name: kernel.event_subscriber }

  app.event.group:
    class: AppBundle\EventSubscriber\GroupActivitySubscriber
    arguments: ["@doctrine", "@logger"]
    tags:
        - { name: kernel.event_subscriber }

