services:
  app.event.user:
    class: AppBundle\EventListener\UserActivityEventListener
    arguments: ["@service_container"]
    tags:
      - { name: kernel.event_listener, event: app.event.user.add, method: userAdd }
      - { name: kernel.event_listener, event: app.event.user.update, method: userUpdate }
      - { name: kernel.event_listener, event: app.event.user.delete, method: userDelete }
  app.event.group:
    class: AppBundle\EventListener\GroupActivityEventListener
    arguments: ["@service_container"]
    tags:
      - { name: kernel.event_listener, event: app.event.group.add, method: groupAdd }
      - { name: kernel.event_listener, event: app.event.group.update, method: groupUpdate }
      - { name: kernel.event_listener, event: app.event.group.delete, method: groupDelete }
      - { name: kernel.event_listener, event: app.event.group.useradd, method: groupUserAdd }
      - { name: kernel.event_listener, event: app.event.group.userupdate, method: groupUserUpdate }
      - { name: kernel.event_listener, event: app.event.group.userdelete, method: groupUserDelete }
