services:
  app.manager.user_group:
    class: AppBundle\Manager\UserGroupManager
    arguments: ["@doctrine"]

  app.event.user:
    class: AppBundle\EventSubscriber\UserActivitySubscriber
    arguments: ["@doctrine", "@logger"]
    tags:
        - { name: kernel.event_subscriber }

  app.event.group:
    class: AppBundle\EventSubscriber\GroupActivitySubscriber
    arguments: ["@doctrine", "@logger"]
    tags:
        - { name: kernel.event_subscriber }
