services:
  app.manager.user:
    class: AppBundle\Manager\UserManager
    arguments: ["@doctrine", "@event_dispatcher"]

  app.manager.group:
    class: AppBundle\Manager\GroupManager
    arguments: ["@doctrine", "@event_dispatcher"]

  app.manager.membership:
    class: AppBundle\Manager\MembershipManager
    arguments: ["@doctrine", "@event_dispatcher"]

  app.manager.user_group:
    class: AppBundle\Manager\UserGroupManager
    arguments: ["@doctrine"]

  app.manager.group_in_group:
    class: AppBundle\Manager\GroupInGroupManager
    arguments: ["@doctrine", "@event_dispatcher"]

  app.manager.notification:
    class: AppBundle\Manager\NotificationManager
    arguments: ["@doctrine", "@event_dispatcher", "@app.manager.membership"]

  app.event.user:
    class: AppBundle\EventSubscriber\UserActivitySubscriber
    arguments: ["@doctrine", "@logger"]
    tags:
        - { name: kernel.event_subscriber }

  app.event.group:
    class: AppBundle\EventSubscriber\GroupActivitySubscriber
    arguments: ["@doctrine", "@logger"]
    tags:
        - { name: kernel.event_subscriber }

  app.form.user_in_group:
    class: AppBundle\Form\UserInGroupType
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
        - { name: form.type }

  app.form.group:
    class: AppBundle\Form\UserGroupType
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
        - { name: form.type }

  app.form.group_in_group:
    class: AppBundle\Form\UserGroupInGroupType
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
        - { name: form.type }
