---
# Install some base packages
- name: Install MySQL
  action: apt pkg={{ item }} state=installed update_cache=yes
  with_items:
    - mysql-common
    - mysql-client
    - mysql-server
    - python-selinux
    - python-mysqldb

- name: Set root password
  mysql_user:
    name: root
    host: '{{ item }}'
    password: '{{ mysql_root_password }}'
  with_items:
    - "%"
    - 127.0.0.1
    - ::1
    - localhost

- name: Create configuration file
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf

- name: Copy .my.cnf with root password credentials
  template:
    src: _my.cnf.j2
    dest: ~/.my.cnf
    mode: 0600

- name: Create database "symfony"
  mysql_db:
    name: symfony
    collation: utf8_unicode_ci
    encoding: utf8
    state: present

- service: name=mysql state=stopped

- file: path={{ item }} state=absent
  with_items:
    - /var/lib/mysql/ib_logfile0
    - /var/lib/mysql/ib_logfile1

- service: name=mysql state=started enabled=yes
